export const posts = [
    {
        slug: "building-nyra-voice-ai",
        id: "01",
        title: "Building Nyra: Lessons from Shipping Voice AI",
        excerpt: "What I learned building a production-ready voice-first AI assistant — from latency challenges to conversation memory architecture.",
        content: "Building Nyra taught me that voice AI is fundamentally different from text-based AI. The latency requirements are brutal — users expect responses under 200ms, which means every millisecond of pipeline processing matters. I ended up restructuring the entire architecture around streaming, using LiveKit for real-time WebRTC transport and OpenAI's streaming API for token-by-token generation.\n\nThe conversation memory problem was equally challenging. Unlike chat interfaces where users tolerate context windows, voice conversations demand natural memory recall. I implemented a hybrid approach: short-term memory via sliding context windows, and long-term memory using vector embeddings stored in a persistent database.\n\nThe biggest lesson? Ship the MVP first, then iterate. Nyra v1 was barely functional, but it proved the concept and attracted the feedback I needed to build v2.",
        category: "AI Engineering",
        date: "2026",
        readTime: "8 min read",
        accent: "#4a9eff",
        tags: ["Voice AI", "FastAPI", "OpenAI"],
    },
    {
        slug: "jupyter-to-production",
        id: "02",
        title: "From Jupyter to Production: A Practical Guide",
        excerpt: "The gap between a working notebook and a deployed product is massive. Here's the playbook I use for every AI project.",
        content: "Every data scientist knows the pain: your notebook runs perfectly, but deploying it to production is a nightmare. After shipping multiple AI products, I've developed a systematic approach.\n\nStep 1: Refactor into modules. Notebooks are great for exploration, but production code needs structure. I extract every reusable function into separate modules with proper type hints and docstrings.\n\nStep 2: Add configuration management. Hardcoded paths and parameters are the enemy. I use environment variables and config files from day one.\n\nStep 3: Containerize early. Docker isn't optional — it's essential. I create a Dockerfile as soon as I have a working prototype, ensuring reproducibility across environments.\n\nStep 4: Implement monitoring. Models degrade silently without observability. I add logging, metrics, and alerting before the first deployment.\n\nStep 5: Automate testing. Unit tests for data processing, integration tests for API endpoints, and end-to-end tests for the full pipeline.",
        category: "Engineering",
        date: "2025",
        readTime: "12 min read",
        accent: "#e8b878",
        tags: ["MLOps", "Docker", "Deployment"],
    },
    {
        slug: "why-most-ai-projects-fail",
        id: "03",
        title: "Why Most AI Projects Fail (And How to Fix It)",
        excerpt: "90% of AI projects never make it to production. The problem isn't the model — it's the approach to building products.",
        content: "After working on 10+ AI projects, I've seen the same failure patterns repeat. Here are the three biggest reasons AI projects die, and what to do instead.\n\n1. Starting with the model, not the problem. Teams often pick the latest architecture before understanding what the user actually needs. Start with the simplest solution that could work.\n\n2. Over-engineering from day one. Building a perfect training pipeline before validating the concept is a waste. Use pre-trained APIs and off-the-shelf models first.\n\n3. Ignoring the feedback loop. Shipping to production isn't the finish line — it's the starting line. Build systems that capture user feedback and enable rapid iteration.\n\nThe fix is simple: think like a product engineer, not a researcher. Your job isn't to build the best model — it's to solve the user's problem.",
        category: "Product Thinking",
        date: "2025",
        readTime: "6 min read",
        accent: "#51cf66",
        tags: ["Product", "Strategy", "AI"],
    },
    {
        slug: "multivariate-analysis",
        id: "04",
        title: "Multivariate Analysis: Finding Needles in Data Haystacks",
        excerpt: "How I used PCA and Factor Analysis to reduce 55 manufacturing variables to 3 actionable factors — and what it taught me about data storytelling.",
        content: "Working with high-dimensional manufacturing data is like trying to find patterns in a blizzard. My case study analyzed 1,000 observations across 55 variables to identify root causes of defects.\n\nThe key insight: most variables were correlated. Machine speed, temperature, and pressure weren't independent — they formed latent factors that actually drove defect rates.\n\nUsing PCA, I reduced 55 variables to 3 principal factors explaining 67.94% of variance. Factor Analysis confirmed the structure: a 'Machine Performance' factor, an 'Environmental' factor, and a 'Material Quality' factor.\n\nHotelling's T² control charts revealed that 40% of defects occurred when multiple factors simultaneously deviated from their norms — something univariate analysis completely missed.\n\nThe business impact? A 40% reduction in defect detection time and a clear framework for prioritizing interventions. Sometimes, less data really is more.",
        category: "Data Science",
        date: "2024",
        readTime: "10 min read",
        accent: "#a78bfa",
        tags: ["PCA", "Statistics", "R"],
    },
];

export type BlogPost = (typeof posts)[0];
